### PR TITLE
Add ignorecase option for #39, wrapdiff option for #57

### PR DESCRIPTION
**Pull request by zhudock**

### CODE REVIEW

**Comment by wickedest** [comment]
zhudock - thanks for that.  I made it always wrap the prev/next.  I also added the ignorecase to the Mergely editor.

**Comment by zhudock** [comment]
glad to help. any objections to me creating an [Oracle APEX](https://apex.oracle.com/en/) plugin that includes this tool, so long as I choose a compatible license?

**Comment by zhudock** [comment]
glad to help. any objections to me creating an [Oracle APEX](https://apex.oracle.com/en/) plugin that includes this tool, so long as I choose a compatible license?

**Comment by wickedest** [comment]
No problem.  Give a shout if you have any problems.  I guess LGPL might be the most appropriate.  Feel free to mention the commercial license in a link back to Mergely on github.

**Pull request merged**
