### PR TITLE
Fixes #41: "Scroll to diff" vs "Merge left/right"

### LINKED ISSUE #41: gutterClick: "Scroll to diff" vs "Merge left/right"
On the left hand side, clicking a row number to scroll to/highlight that diff doesn't work.
On the right hand side, clicking the "Merge left" buttons don't work.

tmp7828 tmp

Demo: http://codepen.io/Sphinxxxx/pen/grVvjG
(I'll add a pull request shortly)

### PR DESCRIPTION
**Pull request by Sphinxxxx**

### CODE REVIEW

**Comment by wickedest** [comment]
Thanks.  It needed a minor tweak to get it working.  You should try it, and if you are happy with it, I will cut a new version of Mergely.

**Comment by Sphinxxxx** [comment]
Your `.parentNode` tweak fails on the default editor layout (e.g. the CodePen demo), where there is no extra UI inside the `.merge-button` div. If you change the `if` to this instead...

    if(ev.target && (jQuery(ev.target).closest('.merge-button').length > 0)) {

...that should take care of all cases.

**Comment by wickedest** [comment]
Cut: https://github.com/wickedest/Mergely/releases/tag/3.4.1

**Comment by Sphinxxxx** [comment]
Cool :)

**Pull request merged**
